name: drop_chat
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.9
  cloud_firestore: ^0.14.4
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  flutter_bloc: ^6.1.1
  flutter_hooks: ^0.15.0
  freezed_annotation: ^0.12.0
  get_it: ^5.0.3
  google_sign_in: ^4.5.6
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  injectable: ^1.0.5
  json_annotation: ^3.1.1
  kt_dart: ^0.8.0
  path_provider: ^1.6.24
  provider: ^4.3.2+3
  rxdart: ^0.25.0
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: null
  freezed: ^0.12.6
  hive_generator: ^0.8.2
  injectable_generator: ^1.0.6
  json_serializable: ^3.5.1
  lint: ^1.3.0

flutter:
  uses-material-design: true
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-Medium.ttf
        - asset: assets/fonts/DancingScript-SemiBold.ttf
        - asset: assets/fonts/DancingScript-Bold.ttf
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
